// File generated by Blink v0.18.6 (https://github.com/1Axen/Blink)
// This file is not meant to be edited

export declare const StepReplication: () => void
type data = unknown
type player = unknown
type version = number
type increaseLvl = number
type upgradeType = number
type quantity = number
type addEggFrom = number
type index = number
type name = string
export declare const ProfileUpdated: {
	On: (Listener: (Value1: unknown, Value2: number | undefined) => void) => (() => void)
}
export declare const GetProfile: {
	Invoke: (Value: void) => LuaTuple<[unknown, number | undefined]>
}
