// File generated by Blink v0.18.6 (https://github.com/1Axen/Blink)
// This file is not meant to be edited

export declare const StepReplication: () => void
type data = unknown
type player = unknown
type version = number
export declare const ProfileUpdated: {
	On: (Listener: (Value1: unknown, Value2: number | undefined) => void) => (() => void)
}
export declare const GetProfile: {
	Invoke: (Value: void) => LuaTuple<[unknown, number | undefined]>
}
export declare const Preload: {
	Invoke: (Value: void) => boolean
}
export declare namespace Garden {
	type slot = number
	type plant = string
	export const Init: {
		On: (Listener: (Value: number) => void) => (() => void)
	}
	export const Sow: {
		Fire: (Value: string) => void
	}
}
