// File generated by Blink v0.18.6 (https://github.com/1Axen/Blink)
// This file is not meant to be edited

export declare const StepReplication: () => void
type data = unknown
type player = unknown
type version = number
export declare const ProfileUpdated: {
	Fire: (Player: Player, Value1: unknown, Value2: number | undefined) => void
	FireAll: (Value1: unknown, Value2: number | undefined) => void
	FireExcept: (Except: Player, Value1: unknown, Value2: number | undefined) => void
	FireList: (List: Player[], Value1: unknown, Value2: number | undefined) => void
}
export declare const GetProfile: {
	On: (Listener: (Player: Player, Value: void) => LuaTuple<[unknown, number | undefined]>) => void
}
export declare const Preload: {
	On: (Listener: (Player: Player, Value: void) => boolean) => void
}
export declare namespace Garden {
	type slot = number
	type plant = string
	export const Init: {
		Fire: (Player: Player, Value: number) => void
		FireAll: (Value: number) => void
		FireExcept: (Except: Player, Value: number) => void
		FireList: (List: Player[], Value: number) => void
	}
	export const Sow: {
		On: (Listener: (Player: Player, Value: string) => void) => (() => void)
	}
}
