local CONSTANTS = {

	TIP_MESSAGES = {
		"Serve hot food fast — customers tip more for quick service.",
		"Keep stations organized to reduce prep time.",
		"Upgrade ovens and fryers to speed up cooking.",
		"Polite staff = happier customers = bigger tips.",
		"Combo orders (drink + main) increase average spend.",
		"Clean tables quickly to raise customer patience.",
		"Prioritize VIP customers — they tip higher.",
		"Rush hour: focus on throughput, not perfection.",
		"Pre-cook common items during quiet times.",
		"Use boosters during events to double tips.",
		"Specials attract new customers — rotate them daily.",
		"Balance menu variety with prep complexity.",
		"Customers prefer consistent quality over flashy items.",
		"Learn each customer's favorite — repeat business follows.",
		"A friendly greeting increases tip chance.",
		"Serve sides together with mains to avoid delays.",
		"Upgrade seating to serve more customers at once.",
		"Keep an eye on order timers to avoid refunds.",
		"Train staff to handle two tasks at once.",
		"Offering small discounts can boost long-term profit.",
		"Accepting large orders needs extra staff on shift.",
		"Stagger item cook times to minimize finishing jams.",
		"Use express lanes for takeout customers.",
		"Daily quests encourage repeat visits — add them!",
		"Customer patience increases with comfortable seating.",
		"Crowd control prevents unhappy customers during rush.",
		"Decor and music slightly increase tip amounts.",
		"Surprise freebies (small dessert) boost tips.",
		"Track popular items and remove low-sellers.",
		"Seasonal menus keep players coming back.",
		"Keep menu icons clear — players choose faster.",
		"Allow quick-reorder of recent meals to speed play.",
		"Auto-save player progress whenever they close.",
		"Show order previews so players can prepare early.",
		"A progress bar for plates reduces player stress.",
		"Tutorial: teach serving order priority early.",
		"Balance price vs. prep time for meaningful choices.",
		"Add achievements for consecutive perfect services.",
		"Customer types: regulars, VIPs, critics — treat them differently.",
		"Power-ups should feel fun, not mandatory.",
		"Allow cosmetic upgrades so players can personalize.",
		"Make daily goals short and achievable to retain players.",
		"Add a 'rush meter' so players know when to brace.",
		"Give feedback sounds for good/bad service moments.",
		"Use color cues on orders to show urgency.",
		"Small UI hints reduce player confusion in busy moments.",
		"Leaderboard boosts friendly competition and retention.",
		"Balance monetization: convenience is OK, paywall is not.",
		"Save server-side player progression to avoid loss.",
		"Keep new-player onboarding under 2 minutes.",
		"Player-made recipes = fun user-generated content!",
	},

}

return CONSTANTS
